version: "3.9"
   
services:
  slicemanager:
    build: ./slicemanager/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./slicemanager/:/code
    ports:
      - "8001:8000"

  cybersecmodule:
    build: ./cybersecmodule/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cybersecmodule/:/code
    ports:
      - "8002:8000"
