# Generated by Django 3.1.3 on 2020-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slicehpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_identifier', models.CharField(max_length=200)),
                ('security_status', models.CharField(max_length=200, null=True)),
                ('openstack_security_rules', models.CharField(max_length=2000, null=True)),
                ('opendaylight_security_rules', models.CharField(max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
