# Generated by Django 3.1.4 on 2020-12-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slicehpc',
        ),
    ]
