# Generated by Django 3.1.4 on 2020-12-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slicehpc',
            name='security_request_body',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
